import Providers from "@/components/Providers";
import AppSidebar from "@/components/shared/AppSidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import React from "react";

export const metadata: Metadata = {
  title: "AdTalk DMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <NuqsAdapter>
          <div vaul-drawer-wrapper="">
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <main className="flex flex-1 flex-col">{children}</main>
              </SidebarInset>
            </SidebarProvider>
          </div>
        </NuqsAdapter>
      </ThemeProvider>
    </Providers>
  );
}
