import Providers from "@/components/Providers";
import AppSidebar from "@/components/shared/AppSidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { getSession } from "@/lib/auth";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "AdTalk DMS",
  description: "Generated by create next app",
};

const client = new QueryClient();

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = (await getSession()).user;

  return (
    <Providers>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div vaul-drawer-wrapper="">
          <SidebarProvider>
            <AppSidebar user={user} />
            <SidebarInset>
              <main className="flex flex-1 flex-col gap-4">{children}</main>
            </SidebarInset>
          </SidebarProvider>
        </div>
      </ThemeProvider>
    </Providers>
  );
}
