import Providers from "@/components/Providers";
import AppSidebar from "@/components/shared/AppSidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { LoadingSpinner } from "@/components/ui/loading-spinner";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { getUserById } from "@/lib/actions/user.actions";
import { getSession } from "@/lib/session";
import { LoaderIcon } from "lucide-react";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import React, { Suspense } from "react";

export const metadata: Metadata = {
  title: "AdTalk DMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  if (!session) {
    redirect("/login");
  }
  const user = await getUserById(session.userId, session.access);

  if (!user.data) {
    throw Error("User not found");
  }

  return (
    <Providers>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div vaul-drawer-wrapper="">
          <SidebarProvider>
            <AppSidebar user={user.data} />
            <SidebarInset>
              <Suspense
                fallback={
                  <div className="flex flex-1 items-center justify-center">
                    <LoaderIcon className="animate-spin" />
                  </div>
                }
              >
                <main className="flex flex-1 flex-col">{children}</main>
              </Suspense>
            </SidebarInset>
          </SidebarProvider>
        </div>
      </ThemeProvider>
    </Providers>
  );
}
