name: Deploy Project

on:
  pull_request:
    branches: ["main"]
    types: [closed] # triggers when a PR is closed or merged into 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run this job if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2

      - name: Deploy with Coolify
        uses: marconneves/coolify-actions@v0.0.4
        with:
          coolify-url: ${{ secrets.COOLIFY_URL }}
          coolify-app-id: ${{ secrets.COOLIFY_APP_ID }}
          coolify-token: ${{ secrets.COOLIFY_TOKEN }}
